spring:
  security:
    user:
      name: foo
      password: foo
  profile: dev
  data:
    mongodb:
      uri:  mongodb://localhost:27017/niyo
      url:  mongodb://localhost:27017/niyo
      host: localhost
      port: 27017
      database: niyo
      hidden_node_uri: mongodb://localhost:27017/niyo
      authEnabled: false
